#!/usr/bin/env bash

DB_USER=
DB_PW=
DB_DATABASE=

echo "SELECT id, code, name FROM courses" | mysql -B --skip-column-names -u$DB_USER -p$DB_PW $DB_DATABASE > courses.tab
echo "SELECT id, login, password, joined_date, last_seen_date, email, access_level FROM users" | mysql -B --skip-column-names -u$DB_USER -p$DB_PW $DB_DATABASE > users.tab
echo "SELECT id, code, name FROM languages" | mysql -B --skip-column-names -u$DB_USER -p$DB_PW $DB_DATABASE > langs.tab
echo "SELECT id, course_id, date, language_id, submitted_by, submission_date, description FROM exams" | mysql -B --skip-column-names -u$DB_USER -p$DB_PW $DB_DATABASE > exams.tab
echo "SELECT id, exam_id, location FROM files" | mysql -B --skip-column-names -u$DB_USER -p$DB_PW $DB_DATABASE > files.tab
